/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaraKerjaRouteImport } from './routes/cara-kerja'
import { Route as CatatRouteImport } from './routes/catat'
import { Route as CekRouteImport } from './routes/cek'
import { Route as VerifikasiRouteImport } from './routes/verifikasi'
import { Route as ArsipIndexRouteImport } from './routes/arsip.index'
import { Route as ArsipIdRouteImport } from './routes/arsip.$id'
import { Route as HasilIndexRouteImport } from './routes/hasil.index'
import { Route as HasilWorkIdRouteImport } from './routes/hasil.$workId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaraKerjaRoute = CaraKerjaRouteImport.update({
  id: '/cara-kerja',
  path: '/cara-kerja',
  getParentRoute: () => rootRouteImport,
} as any)
const CatatRoute = CatatRouteImport.update({
  id: '/catat',
  path: '/catat',
  getParentRoute: () => rootRouteImport,
} as any)
const CekRoute = CekRouteImport.update({
  id: '/cek',
  path: '/cek',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifikasiRoute = VerifikasiRouteImport.update({
  id: '/verifikasi',
  path: '/verifikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const ArsipIndexRoute = ArsipIndexRouteImport.update({
  id: '/arsip/',
  path: '/arsip/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArsipIdRoute = ArsipIdRouteImport.update({
  id: '/arsip/$id',
  path: '/arsip/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HasilIndexRoute = HasilIndexRouteImport.update({
  id: '/hasil/',
  path: '/hasil/',
  getParentRoute: () => rootRouteImport,
} as any)
const HasilWorkIdRoute = HasilWorkIdRouteImport.update({
  id: '/hasil/$workId',
  path: '/hasil/$workId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cara-kerja': typeof CaraKerjaRoute
  '/catat': typeof CatatRoute
  '/cek': typeof CekRoute
  '/verifikasi': typeof VerifikasiRoute
  '/arsip/$id': typeof ArsipIdRoute
  '/hasil/$workId': typeof HasilWorkIdRoute
  '/arsip/': typeof ArsipIndexRoute
  '/hasil/': typeof HasilIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cara-kerja': typeof CaraKerjaRoute
  '/catat': typeof CatatRoute
  '/cek': typeof CekRoute
  '/verifikasi': typeof VerifikasiRoute
  '/arsip/$id': typeof ArsipIdRoute
  '/hasil/$workId': typeof HasilWorkIdRoute
  '/arsip': typeof ArsipIndexRoute
  '/hasil': typeof HasilIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cara-kerja': typeof CaraKerjaRoute
  '/catat': typeof CatatRoute
  '/cek': typeof CekRoute
  '/verifikasi': typeof VerifikasiRoute
  '/arsip/$id': typeof ArsipIdRoute
  '/hasil/$workId': typeof HasilWorkIdRoute
  '/arsip/': typeof ArsipIndexRoute
  '/hasil/': typeof HasilIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cara-kerja'
    | '/catat'
    | '/cek'
    | '/verifikasi'
    | '/arsip/$id'
    | '/hasil/$workId'
    | '/arsip/'
    | '/hasil/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cara-kerja'
    | '/catat'
    | '/cek'
    | '/verifikasi'
    | '/arsip/$id'
    | '/hasil/$workId'
    | '/arsip'
    | '/hasil'
  id:
    | '__root__'
    | '/'
    | '/cara-kerja'
    | '/catat'
    | '/cek'
    | '/verifikasi'
    | '/arsip/$id'
    | '/hasil/$workId'
    | '/arsip/'
    | '/hasil/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaraKerjaRoute: typeof CaraKerjaRoute
  CatatRoute: typeof CatatRoute
  CekRoute: typeof CekRoute
  VerifikasiRoute: typeof VerifikasiRoute
  ArsipIdRoute: typeof ArsipIdRoute
  HasilWorkIdRoute: typeof HasilWorkIdRoute
  ArsipIndexRoute: typeof ArsipIndexRoute
  HasilIndexRoute: typeof HasilIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cara-kerja': {
      id: '/cara-kerja'
      path: '/cara-kerja'
      fullPath: '/cara-kerja'
      preLoaderRoute: typeof CaraKerjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catat': {
      id: '/catat'
      path: '/catat'
      fullPath: '/catat'
      preLoaderRoute: typeof CatatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cek': {
      id: '/cek'
      path: '/cek'
      fullPath: '/cek'
      preLoaderRoute: typeof CekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifikasi': {
      id: '/verifikasi'
      path: '/verifikasi'
      fullPath: '/verifikasi'
      preLoaderRoute: typeof VerifikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arsip/': {
      id: '/arsip/'
      path: '/arsip'
      fullPath: '/arsip/'
      preLoaderRoute: typeof ArsipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arsip/$id': {
      id: '/arsip/$id'
      path: '/arsip/$id'
      fullPath: '/arsip/$id'
      preLoaderRoute: typeof ArsipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hasil/': {
      id: '/hasil/'
      path: '/hasil'
      fullPath: '/hasil/'
      preLoaderRoute: typeof HasilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hasil/$workId': {
      id: '/hasil/$workId'
      path: '/hasil/$workId'
      fullPath: '/hasil/$workId'
      preLoaderRoute: typeof HasilWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaraKerjaRoute: CaraKerjaRoute,
  CatatRoute: CatatRoute,
  CekRoute: CekRoute,
  VerifikasiRoute: VerifikasiRoute,
  ArsipIdRoute: ArsipIdRoute,
  HasilWorkIdRoute: HasilWorkIdRoute,
  ArsipIndexRoute: ArsipIndexRoute,
  HasilIndexRoute: HasilIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
